# installs
# install: true

#language
language: php

#php versions
php:
  - '7.1.7'

# 째_째
env: # important!
# 째_째

# scripts:
#  - phpunit

# notifications
notifications:
  email: false
  slack:
      on_success: always
      on_failure: always
